### ISSUE TITLE
III stage

### ISSUE THREAD

**Issue by rusdevops** [KonstantinPronin/InstagramClient#1]
@KonstantinPronin 

 - [x] 1. Отсутствует проверка корректного состояния стандартного потока ввода. 
[здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/examples/main.cpp#L12), [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/examples/main.cpp#L29) и [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/sources/client.cpp#L99).
- [x] 2. Не корректное именование локальной переменной. [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/examples/main.cpp#L15).
- [x] 3. Присутствует избыточная оптимизация. [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/sources/client.cpp#L77).
- [x] 4. Присутствует не оптимальное размещение инструкций. [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/sources/client.cpp#L82) и [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/sources/client.cpp#L87).
- [x] 5. Присутствует не оптимальное использование операторов. [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/sources/client.cpp#L112).
- [x] 6. Использование устаревшей языковой конструкции. [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/sources/client.cpp#L110).
- [x] 7. Отсутствует проверка корректного состояния потока. [здесь](https://github.com/KonstantinPronin/InstagramClient/blob/efc13ce1186f27c06b570690439b27fce265152e/sources/client.cpp#L118).

**Comment by prosayfer** [comment]
1. Исправлено.
2. Если я правильно понял, то нужно было писать имя строчными символами, в таком случае исправил.
3. Имеется в виду аргумент const bool&?
4. Имеется в виду, что время засекается после нескольких других строк(захват мьютекса) или что оно засекается в любом случае вне зависимости от наличия ключа '-v'?
5. Не понял, можно поконкретнее? 
6. Исправлено.
7. Зачем использовать std::thread::joinable в данной ситуации? Объекты std::thread инициализируются в цикле, затем для каждого вызывается единственный join, в каком случае может быть некорректное состояние?

**Comment by rusdevops** [comment]
3. yes.
5. `i++ vs ++i` ?
7. Exceptions `http://en.cppreference.com/w/cpp/thread/thread/join`.

**Comment by prosayfer** [comment]
3. Исправил.
4. Разве имеет значение для типа size_t?
https://habrahabr.ru/company/pvs-studio/blog/113661/
5. Исправил.

**Comment by rusdevops** [comment]
Возвращаймый тип [hardware_concurrency](http://ru.cppreference.com/w/cpp/thread/thread/hardware_concurrency) `unsigned int`. 
Замените `size_t` на `unsigned int`. 
Имеет значение для согласованности с другими вызовами оператора `++`.

```
for (auto i = 0; i < n; ++i) {

...

for (; it < end; ++it) {

...

for (auto i = 0; i < n; ++i) {

...

for (; it < end; ++it) {
```

**vs**

```
for (auto i = 0; i < n; ++i) {

...

for (; it < end; it++) {

...

for (auto i = 0; i < n; ++i) {

...

for (; it < end; ++it) {
```
